version: '3.9'

services:
  key_to_cap_postgres:
    container_name: key_to_cap_postgres
    image: postgres:16.2
    environment:
      POSTGRES_USER: key_to_cap
      POSTGRES_PASSWORD: key_to_cap
      PGDATA: /data/postgres
    volumes:
      - postgres:/var/www/key_to_cap/docker-volumes/postgres
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - key_to_cap
    restart: unless-stopped

networks:
  key_to_cap:
    driver: bridge

volumes:
  postgres:
