version: '3.5'

services:
  key_to_cap_postgres:
    container_name: key_to_cap_postgres
    image: postgres:14
    environment:
      POSTGRES_USER: key_to_cap
      POSTGRES_PASSWORD: key_to_cap
      PGDATA: /data/postgres
    volumes:
      - postgres:/var/www/key_to_cap/docker-volumes/postgres
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - key_to_cap
    restart: unless-stopped

  key_to_cap_pgadmin:
    container_name: key_to_cap_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: key_to_cap@admin.com
      PGADMIN_DEFAULT_PASSWORD: key_to_cap
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/www/key_to_cap/docker-volumes/pgadmin
    ports:
      - 127.0.0.1:5050:80
    networks:
      - key_to_cap
    restart: unless-stopped

networks:
  key_to_cap:
    driver: bridge

volumes:
  postgres:
  pgadmin:
